### ISSUE TITLE
Visual Studio Intellisense does not update when regenerating IDE files with changes to the header search paths

### ISSUE THREAD

**Issue by lacasseio** [nokeedev/gradle-native#103]
We may consider deleting .vs folder on IDE files generation: https://weblog.west-wind.com/posts/2018/Aug/07/Fixing-Visual-Studio-Intellisense-Errors#clearing-up-intellisense

**Comment by max-ag** [comment]
One problem with deleting the .vs folder, although it fixes problems with Intellisense, is that the folder is locked by VS when the solution is opened.

**Comment by lacasseio** [comment]
I was suspecting that would be the case, we can tentatively delete the folder and issue a warning to the user or simply fail without modifying any visual studio files to let the user close the solution. We can also open the process and force close the handle ;-)

More research will be required.

**Comment by lacasseio** [comment]
We should at least provide a warning message before GA.

**Comment by lacasseio** [comment]
@max-ag Could you try reproducing the error but use this menu to see if you could force Visual Studio to rescan with new information?

<img width="655" alt="Screen Shot 2020-07-23 at 12 21 04 PM" src="https://user-images.githubusercontent.com/22181740/88276347-e2d0d700-ccac-11ea-827b-c91b9f4f982c.png">

**Comment by lacasseio** [comment]
There's also the same option in the `Project` menu:

<img width="387" alt="Screen Shot 2020-07-23 at 12 29 04 PM" src="https://user-images.githubusercontent.com/22181740/88276966-eadd4680-ccad-11ea-98ab-b8a8574d7456.png">

**Comment by max-ag** [comment]
Using "Rescan Solution" from either menus seems to have the same behavior as deleting the .vs folder. (i.e. it fixes the Intellisense errors).

**Comment by lacasseio** [comment]
Excellent, I will add some logic to detect the solution is open and issue a warning on the steps to follow. I will also add a note in the user manual chapter on why this is needed.
