### ISSUE TITLE
Generated Visual Studio project names are truncated

### ISSUE THREAD

**Issue by max-ag** [nokeedev/gradle-native#107]
If you have a project called `foo:bar`, it'll show up as `bar` in the Visual Studio solution. It should follow the original name of the project, or at least be named something like `foo_bar`, or `foo-bar`.

**Comment by lacasseio** [comment]
This is an issue the Gradle core visual studio support has a workaround for. I'm unsure if we want the same solution for Nokee. We already diverge in our solution and would rather use the model path instead of replacing path separator with underscores. An experimentation is required before proceeding.

**Comment by lacasseio** [comment]
This issue is the same for Xcode IDE plugin.

**Comment by lacasseio** [comment]
Visual Studio IDE project and Xcode IDE project/group name are based on the Gradle project name and component basename. In theory, they should not overlap unless a user is producing two tools/library with the same name from different projects. The projects will look like the following based on 2 projects (`:`, and `:include`) where the root project produce an application and a unit test.

<img width="1021" alt="Screen Shot 2020-07-23 at 11 53 50 AM" src="https://user-images.githubusercontent.com/22181740/88288997-8ed0ed00-ccc2-11ea-8b27-5e54f75ffa98.png">


@max-ag Can you confirm that based on your projects, this is acceptable?

**Comment by lacasseio** [comment]
It was confirmed this is good enough at the moment. Edge cases will be handled by #86.
