### ISSUE TITLE
JavaVM framework with XCode 12.2 / macOS 11.0

### ISSUE THREAD

**Issue by weisJ** [nokeedev/gradle-native#215]
From XCode version 12.2 onwards the framwork set of macOS 11.0 is used, which doesn't include the JavaVM framework.
Of course an installation of the Jdk still should include these files, so a new method to discover the JavaVM framework may be needed.

[Relevant stackoverflow question](https://stackoverflow.com/questions/64844595/javacpp-builds-failing-on-macos-after-xcode-12-2-update-due-to-missing-javavm-fr)

For now the solution is to stay on XCode 12.1. For github actions this can be easily achieved using [this action](https://github.com/marketplace/actions/setup-xcode-version).

**Comment by lacasseio** [comment]
Thanks for the information, I will look at it this week.

**Comment by lacasseio** [comment]
Here is a build scan of the error: https://scans.gradle.com/s/uy66kyto7f3vc/tests/:docs:docsTest/dev.nokee.docs.samples.jni.JniLibraryWithFrameworkDependenciesSampleTest/can%20execute%20commands%20successfully%5B1%5D#1

**Comment by lacasseio** [comment]
The situation isn't ideal for this particular framework given Apple sort-of free-styled the framework division. JavaVM framework has been deprecated for a long time now but included the important JavaNativeFoundation framework. Subframework is supposed to be an implementation detail of the framework but JavaVM is particular as people were using its subframeworks. In the newer Xcode, JavaVM is gone but JavaNativeFoundation is not a top-level framework. My guess is it should still work if we declare a dependency on `nativeImplementation 'dev.nokee.framework:JavaNativeFoundation:latest.release'`. These two frameworks may require some special handling so users can just depend on `JavaNativeFoundation` and we would discover it regardless if it's a sub-framework or a system framework.

Note that JavaVM can be found at `/System/Library/Frameworks/JavaVM.framework` but it's only for runtime, it doesn't include any headers, subframework or libraries to link against.

There is some work that needs to happen in the system component discovery so I'm unsure if I will spend some time now to add an exception or later. @weisJ Could you see if using a dependency directly on `JavaNativeFoundation` works for you? Also, do you need to build on earlier versions of Xcode? The quick fix right now would be to conditionally configure the dependencies based on which version of Xcode is used. Unfortunately, we don't offer a way to query which Xcode version will be used, yet. The best way would be to use the environment already declared.

<img width="1618" alt="Screen Shot 2020-12-16 at 1 41 28 PM" src="https://user-images.githubusercontent.com/22181740/102391958-6d8bd880-3fa4-11eb-904b-1cace30ca618.png">

**Comment by lacasseio** [comment]
This should be the fix for Xcode 12.2 and later: https://github.com/nokeedev/gradle-native/pull/220/files

Tell me if that works for you, I will open a different issue around adding special treatment for `JavaNativeFoundation`.

**Comment by weisJ** [comment]
> This should be the fix for Xcode 12.2 and later: https://github.com/nokeedev/gradle-native/pull/220/files
> 
> Tell me if that works for you, I will open a different issue around adding special treatment for `JavaNativeFoundation`.

This works for me. Thank you very much!

 

>Also, do you need to build on earlier versions of Xcode? The quick fix right now would be to conditionally configure the dependencies based on which version of Xcode is used. Unfortunately, we don't offer a way to query which Xcode version will be used, yet. The best way would be to use the environment already declared.

I myself don't need to build on earlier versions of XCode as the libraries are build using github actions. However if one wishes to build the project locally he might run into problems when using an earlier version of the problem. I don't think that choosing the dependency based on the XCode version would be the best (idiomatic) way to solve the problem. 

What I think would be a good idea is to have "soft" dependencies which are allowed to be missing. Then one could declare both dependencies as only ever one of both will be available. If no suitable dependency is available it would be nice to have the option for a silent failure (which would just issue a warning and mark the component unbuildable), which would allow for using pre-build libraries as a fallback without a failure. What do you think about this?

**Comment by lacasseio** [comment]
That makes sense, it would be a lenient configuration. Hopefully, I can soon get the ability for adding Gradle configuration from Nokee component directly which will allow you to do exactly that.

**Comment by lacasseio** [comment]
We will continue this work with https://github.com/nokeedev/gradle-native/issues/221. As explained in this issue, the dependencies changed on the Apple/Xcode side. Using the right coordinate will work without issue. Most of the solutions here can be handled via normal Gradle configuration. The pain point is mostly around synching Gradle configuration with Nokee configuration which will be addressed in another milestone: https://github.com/nokeedev/gradle-native/milestone/13
