### ISSUE TITLE
[Question]: Finding included headers in other tasks

### ISSUE THREAD

**Issue by simolus3** [nokeedev/gradle-native#259]
I'm building a JNI library with nokee plugins, and I'm trying to integrate clang-tidy into my build.

At the moment I'm using a custom task like this:

<details>
<summary>Task definition</summary>

```kotlin
abstract class ClangTidy : DefaultTask() {

    @get: Incremental
    @get: InputFiles
    val input = project.files("src/main/c")

    @get: InputFiles
    val includes = project.objects.fileCollection()

    @get: Input
    val checks = project.objects.listProperty(String::class).convention(listOf("-*",  "readability-*"))

    @get: OutputFile
    val output = File(project.buildDir, "tmp/clang-tidy/out.stamp")

    @TaskAction
    fun run(changes: InputChanges) {
        changes.getFileChanges(input).forEach { change ->
            if (change.fileType != FileType.FILE || change.changeType == ChangeType.REMOVED) return@forEach

            project.exec {
                executable = "clang-tidy"

                val arguments = mutableListOf<String>(
                    change.file.path,
                    "--checks=${checks.get().joinToString(",")}",
                    "--"
                )
                for (headers in includes) {
                    arguments.add("-I$headers")
                }

                args(arguments)
            }.assertNormalExitValue()
        }
    }
}
```
</details>

When I configure that task, I need to provide the included headers, like this:

```kotlin
val checkStyle = tasks.register<ClangTidy>("checkStyle") {
    dependsOn("classes") // Generate JNI-headers
    includes.from("src/main/headers", "build/generated/jni-headers")
}
```

However, I'm still missing out on the JNI headers shipped with the JDK and headers from dependencies. I tried to extract them from the `CCompile` tasks, but without much luck. Is there a way to find all included headers so that I could pass them to clang-tidy?

**Comment by lacasseio** [comment]
The best way to achieve this is to get the headers straight from the compile tasks. Unfortunately, it's the present single source of truth. I would like to move them into a more accessible location in the long term. I'm assuming you are creating a single ClangTidy task per project. In that case, I would do something like the following:

```
def includes = application.developmentVariant
    .flatMap { it.developmentBinary }
    .flatMap { it.compileTasks.filter(CCompile) }
    .flatMap { 
        // assuming only one compile source set which should be the default
        def compileTask = it.first()

        // You will have to use the implementation class for compileTask which is AbstractNativeCompileTask in Gradle codebase
        return providers.zip(compileTask.includes.elements, compileTask.systemIncludes.elements)
}
```

The code snippet is in Groovy DSL. My experience with the Kotlin DSL is quite limited so if there is any issue you encounter that is not following the Kotlin mentality, don't hesitate to open an issue, I will look at improving the integration.

It's a bit messy, but you should be able to make it work with what is already present in the latest nightly at the very least. I opened https://github.com/nokeedev/gradle-native/issues/260 to demonstrate this use case and implement any quality of life improvement the the plugins.

**Comment by simolus3** [comment]
Thank you, this helped a lot! I was able to get it working in Kotlin as well. If anyone else stumbles on this, this is how I got it working (using `library` instead of `application` because I'm building a JNI library):

```Kotlin
val checkStyle by tasks.registering<ClangTidy> {
    // Generate JNI-headers
    dependsOn("classes")

    val headers = library
        .variants
        .flatMap { lib ->
            lib.sharedLibrary.compileTasks
                .get()
                .filterIsInstance<CCompile>()
        }
        .flatMap { (task) ->
            providers.provider {
                task.includes.elements.get() + task.systemIncludes.elements.get()
            }
        }

    includes.setFrom(headers)
}
```

That definitely isn't an idiomatic use of providers, but it appears to work...

I couldn't get `providers.zip` to work though: The only `zip` function I see appears to be for a pairwise combinator, but I think we need to just concatenate them?

**Comment by lacasseio** [comment]
I forgot to mention the `providers.zip` is a newer Gradle feature. I have to rebase all my sample to the latest released now that I'm working with a single version of all the documentation. I will help users kickstart project using the latest Gradle instead of the minimum supported version (e.g. 6.2.1). The issue I see with your second flatmap is the lost of task dependencies. The alternative would be to create a file collection and add both `includes` and `systemIncludes` file collection to it. This will reserve any task dependencies. Something like the following:

```
.flatMap { (task) ->
    project.files(task.includes, task.systemIncludes).elements
}
```

**Comment by simolus3** [comment]
Thanks for the pointers! I've now figured out how to use `zip` too:

```kotlin
providers.zip(task.includes.elements, task.systemIncludes.elements) { inc, sys -> inc + sys }
```

That's probably what you meant originally, I was just missing the combiner.
