### ISSUE TITLE
'api' configuration conflicts with kotlin plugin

### ISSUE THREAD

**Issue by javenwang** [nokeedev/gradle-native#31]
Hi, I'm trying to use this great plugin with Kotlin as the Java side language. I received the error after adding kotlin plugin along with jni-library as below:

```kotlin
plugins {
    kotlin("jvm") version "1.3.72"
    id("dev.nokee.jni-library")
    id("dev.nokee.cpp-language")
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform(kotlin("bom")))

    // Use the Kotlin JDK 8 standard library.
    implementation(kotlin("stdlib-jdk8"))

    // Use the Kotlin test library.
    testImplementation(kotlin("test"))

    // Use the Kotlin JUnit integration.
    testImplementation(kotlin("test-junit"))
}

// ...
```

here is the error message:
```shell
$ ./gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/javenwang/demo/build.gradle.kts' line: 1

* What went wrong:
An exception occurred applying plugin request [id: 'dev.nokee.jni-library', artifact: 'dev.nokee.jni-library:dev.nokee.jni-library.gradle.plugin:0.2.0']
> Failed to apply plugin [id 'dev.nokee.jni-library']
   > Could not create an instance of type dev.nokee.platform.jni.internal.JniLibraryDependenciesInternal.
      > Cannot add a configuration with name 'api' as a configuration with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

`jni-library` plugin will create 'api' without checking if it already exists or not (that is why it is incompatible with the Java Library Plugin and Java Application Plugin):
https://github.com/nokeedev/gradle-native/blob/c9183e00aa76e2d9dda9a4eaebaa793800d33bfb/subprojects/platform-jni/src/main/java/dev/nokee/platform/jni/internal/JniLibraryDependenciesInternal.java#L24

IMHO, could we use `maybeCreate()` instead of `create()` to create 'api' configuration here?

**Comment by lacasseio** [comment]
You are right. There isn't any Kotlin compatibility test mostly because I don't have enough experience with the language and especially with JNI. Would you mind pointing me to a Kotlin sample that uses JNI? I can push a sample and fix the issues for the next release that should be done early next week.

**Comment by javenwang** [comment]
It’s my pleasure.

**Comment by lacasseio** [comment]
I should just add now before you do any work. I found a Kotlin/JNI sample, there is no need to provide one. I should have something out in the snapshot soon.

**Comment by lacasseio** [comment]
This sample should show you exactly what you are looking: https://nokee.dev/docs/nightly/samples/kotlin-cpp-jni-library/

Use the version from that sample which is the latest nightly and report back if you encounter any other issue. Cheers!

**Comment by lacasseio** [comment]
The latest nightly in this case is version `0.3.0-bfc9dcb`.

**Comment by javenwang** [comment]
It seems that sample works on Gradle 6.2.1 but not 6.4:
```shell
$ ./gradlew wrapper --gradle-version 6.4

BUILD SUCCESSFUL in 5s
1 actionable task: 1 executed
```
```shell
$ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'kotlin-cpp-jni-library'.
> Could not create task ':compileJava'.
   > Task ':compileJava' property 'options.headerOutputDirectory' is already declared as an output property of task ':compileJava' property 'options' (type CompileOptions). Cannot also declare it as an output property of task ':compileJava' (type JavaCompile).

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

Should it be a new issue?

**Comment by lacasseio** [comment]
Thanks for trying it out. It's a great coincidence as during the night I gave a try to a cross-Gradle version tests: minimum supported (6.2.1), latest GA (6.4) and latest nightly (6.5-...). The newer Gradle test showed the same error, which is the one you pointed out. I will fix it today and hopefully enable the cross-version test permanently. This is tracked as part of https://github.com/nokeedev/gradle-native/issues/18. No need to create another issue.

**Comment by lacasseio** [comment]
Sorry for that failure you got on 6.4. If you use version `0.3.0-2f9eb26` instead, it should be working fine on 6.4. Fix will be released with the next version next week.

**Comment by javenwang** [comment]
Hi @lacasseio , does the plugin generate header files only for Java but not Kotlin?

**Comment by lacasseio** [comment]
Ideally, the plugin would generate the headers regardless of the JVM language. However, at the moment, it uses the Java compiler to do so which I don't think works with Kotlin. According to the research I did, all the example would write their own or convert the Kotlin file to c headers via scripts. I'm very welcoming to any suggestions that may help push this forward.

**Comment by lacasseio** [comment]
I opened this issue https://github.com/nokeedev/gradle-native/issues/38. We can keep going with the discussion over there.
