### ISSUE TITLE
Support dynamic version resolution for framework

### ISSUE THREAD

**Issue by lacasseio** [nokeedev/gradle-native#34]
At the moment, the Nokee plugins will resolve a specific version only. It means that if you request 10.15 but have 10.15.4, the framework will be missing (see https://github.com/weisJ/darklaf/pull/154#issuecomment-625359726). It should provide a list of all the available versions so a dynamic resolution can occur. Something like 10.15.+ would work or any of the other version constraints.

**Comment by lacasseio** [comment]
This will be solved in the next nightly. It supports every dynamic version type.

**Comment by weisJ** [comment]
What is the syntax for dynamic version resolution? I couldn't quite find something in the nightly documentation.

**Comment by lacasseio** [comment]
The syntax should be the same as defined in Gradle core: https://docs.gradle.org/current/userguide/single_versions.html

For good measure, you can refer to these tests to see it in action: https://github.com/nokeedev/gradle-native/blob/master/subprojects/platform-jni/src/functionalTest/groovy/dev/nokee/platform/jni/repositories/ConsumingFrameworkFunctionalTest.groovy#L392-L397

I will open an issue to solve adjust the sample and mention what is allowed.

**Comment by weisJ** [comment]
Thank you :)
