### ISSUE TITLE
an undefined reference/unresolved external symbol 

### ISSUE THREAD

**Issue by ghost** [nokeedev/gradle-native#404]
Will this plugin solve this type of errors ?

https://stackoverflow.com/questions/12573816/what-is-an-undefined-reference-unresolved-external-symbol-error-and-how-do-i-fix

**Comment by poorvajappja** [comment]
I have this error in mac os

![nezee err](https://user-images.githubusercontent.com/65843311/137344429-70c13064-ae9e-4ba0-aeb4-4ce75dc3b631.PNG)

and I have this error in windows os

![nazee err win](https://user-images.githubusercontent.com/65843311/137344500-915e2e34-76f0-4c07-9c4c-78f918dc3855.PNG)

How can I solve this error ?

**Comment by poorvajappja** [comment]
My sample windows project :  https://github.com/poorvajappja/windowsnative

Error occured in my windows project : https://github.com/poorvajappja/windowsnative/runs/3902420596?check_suite_focus=true#step:7:99

My sample mac project : https://github.com/poorvajappja/macnative

Error occured in my mac project : https://github.com/poorvajappja/macnative/runs/3902423312?check_suite_focus=true#step:7:112

How can I solve this error ?

**Comment by lacasseio** [comment]
I pushed a PR on both repositories to give you a good enough demonstration of how to solve the build failure. You are using core native support in Gradle (maintained by the Gradle team) as opposed to the Nokee native support (maintained by me and this repository). I can answer questions on the core native support but I won't provide any fix for that if there is a bug or issue (outside of configuration issue) given my focus is 100% on Nokee.

**Comment by jeevasci** [comment]
How can I solve this error using nokee ?

https://github.com/nokeedev/gradle-native/issues/404#issuecomment-945804712

**Comment by lacasseio** [comment]
When specifying a framework, you need to put the `-framework` flag before each framework you wish to link against. In you case, the command line snippet would look like this `-framework IOKit -framework CoreFoundation`. In the `linkerArgs`, you would need to split each segment into its own string like this: `['-framework', 'IOKit', '-framework', 'CoreFoundation']`. You were simply missing one `-framework` flag in there. You were close ;-).

**Comment by lacasseio** [comment]
This time it's the Core Graphics framework that is missing: https://developer.apple.com/documentation/coregraphics/1456564-cgeventcreatekeyboardevent
