### ISSUE TITLE
No binary is created

### ISSUE THREAD

**Issue by weisJ** [nokeedev/gradle-native#45]
Using version `0.4.0-00ed537` no resulting binary file is produced.

Previously it would appear in `build/libs/main/shared/<variant>/` but now the `main` folder is missing completely.

For example [here](https://github.com/weisJ/auto-dark-mode/runs/704298791?check_suite_focus=true)

**Comment by lacasseio** [comment]
Thanks for trying out the nightly. It's not normal and I will get to the bottom of this today.

**Comment by lacasseio** [comment]
There were two major issues: 1) The version of the Nokee dependencies inside the buildSrc needs to match the plugin version the build will be using and 2) the change to create all binaries as well as differing the creation to the end of the configuration phase broke the uber Jni Jar plugin.

The first error should be solved by providing some sort of BOM for all of Nokee's dependencies so they can be aligned properly (see https://github.com/nokeedev/gradle-native/issues/46).

For the second error, I fix up the code and will submit a PR as soon as a new API makes its way into the next nightly release. As we are differing the creation of the variant until the task graph creation, resolving any of the variants inside a task configuration action will cause a failure. Instead, the provider should only be resolved by Gradle or at execution time so the code has to be shifted around. Hopefully, this won't change much more starting at 0.4.

**Comment by lacasseio** [comment]
PR https://github.com/weisJ/auto-dark-mode/pull/5 should solve the issue you are seeing. I also opened more issues on my side to improve the experience. Thanks a lot for the issue.
