### ISSUE TITLE
Demonstrate how to publish native components targeting multiple machines

### ISSUE THREAD

**Issue by lacasseio** [nokeedev/gradle-native#54]
When targeting multiple machines, it is often the case where all the components are not buildable on the same machine. There are two scenarios possible:
1) Publish incrementally. The first component publish the main artifact that point to non-existing artifact as well as the built components. The other machine publishes its components completing the publication when the last machine publishes its artifacts. This is how the core native plugin in Gradle works. The downside is the possibility for consumers to select a half published library.
2) A variant of the first one but publishing the main components at the end. It would remove the downside of option 1 and avoid a staging step.
3) Stage the publication for an atomic publication. This strategy may be hard to execute if a staging step do not already naturally exists (such as CI keeping built artifacts through the pipeline, see GitHub action).

It feels like option 2 would be the best all-around solution for publishing native components. It's probably the implementation we are going to use for #3

**Comment by lacasseio** [comment]
For more context, see https://github.com/nokeedev/gradle-native/issues/13#issuecomment-600114378

**Comment by DanielSWolf** [comment]
Is this a duplicate of #15? They sound very similar to me.

**Comment by lacasseio** [comment]
Ah yes, you are right. I will close this one and open another issue on spiking the option 2. Thanks for noticing it.

**Comment by lacasseio** [comment]
Spiking option 2 will be done as part of https://github.com/nokeedev/gradle-native/issues/55. This issue is a duplicate of #15.
