### ISSUE TITLE
Pre built binaries: add way to set up task dependencies

### ISSUE THREAD

**Issue by rnett** [nokeedev/gradle-native#552]
I'm using externally build binaries (i.e. I have a task to build them and copy them into `build`, but it's not integrated into nokee).  I'm following https://docs.nokee.dev/samples/jni-library-with-pre-built-binaries/ which works well enough, but I need a way to set up a task dependency on my build task for any consumers of the "prebuilt" binary.  It does not seem like there is an easy way to do this (other than using a task provider to set the property, which works fine).  Would be good to have this in the example, since it's relevant if you're downloading your pre-built binaries or copying/moving them too.

If you can provide some design guidance I can probably PR this myself.  I'm just not sure which tasks need those dependencies.

**Comment by lacasseio** [comment]
In theory, you should just have to make sure the files you add to `nativeRuntimeFiles` are task aware (aka a provider with implicit tasks) and everything should connect correctly. You can also use any task with correctly declared outputs. This is exactly how shared library compilation/linking is wired internally. We could build a sample to show cast this exact scenario or at least add a small mention to the sample.

**Comment by rnett** [comment]
That's what I'm currently doing, and it works well.  For a while, I thought that would be non-trivial and wanted to explicitly specify the task dependencies, which was why I raised this issue, but when I reworked other things it fixed this.  Not sure how much of an issue this is generally.
