### ISSUE TITLE
Build fails if native dependencies aren't available for non-buildable variant

### ISSUE THREAD

**Issue by weisJ** [nokeedev/gradle-native#56]
I am currently migrating Darklaf to the solution used in auto-dark-mode. Building the individual subprojects works fine but when invoking build from the root project it fails, because it tries to resolve the native frameworks (which of course aren't available) although the variant isn't buildable. 

I'm not quite sure why this happens, because building from the root project works fine with auto-dark-mode.

[Build log](https://github.com/weisJ/darklaf/pull/173/checks)

**Comment by lacasseio** [comment]
Ah, yes. I know what's happening. Thanks for the issue, I will work on a fix today.

**Comment by lacasseio** [comment]
Sorry for the delay, I sort of knew where the problem was but I had an issue with reproducing the issue in a test. I push a fix for the issue. The next nightly, version `0.4.0-60cff2b`, should have the fix.

**Comment by weisJ** [comment]
Don't worry. I appreciate your efforts.
