### ISSUE TITLE
Can't find dependent libraries

### ISSUE THREAD

**Issue by Jeevasimba** [nokeedev/gradle-native#587]
**ERROR**

     Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\prade\Documents\jeeva-main\psfe\build\lib\main\psfe.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:287)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2422)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at Pj.nativecodes.<clinit>(nativecodes.java:6)
	at Pj.Launcher.main(Launcher.java:7)

I searched a solution for this error [Answer][1].

How can I solve this error ?

  [1]: https://stackoverflow.com/a/6092576/17777351

**Comment by lacasseio** [comment]
You will have to provide a bit more information than just a call stack. The linked answer is correct and the JNI library plugin should set the `java.library.path` correctly. However, there are other considerations to take into account when loading a native library which is a bit outside of the build system's job and more on the developer's shoulders. If you can provide a small reproducible sample, we can verify if there is an issue with Nokee or guide you toward a solution that fits your need.

**Comment by Jeevasimba** [comment]
Sorry for the late reply.

I am using github action to create jni lib for windows. After creating jni lib from github action I download and check that lib in my computer it worked smoothly.

![qt action](https://user-images.githubusercontent.com/96039278/166094337-48db38be-6481-42f0-9407-201489de1fa5.PNG)


I am using only c++ language in jni side the lib worked on my computer.

But , If I am using c++ with qt framework in jni side. I tested run test in github action the lib gives output in github action. But If I run on my  computer it comes an error like this 

> **ERROR**
> 
> ```
>  Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\prade\Documents\jeeva-main\psfe\build\lib\main\psfe.dll: Can't find dependent libraries
> at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
> at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
> at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
> at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
> at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
> at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:287)
> at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2422)
> at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
> at java.base/java.lang.System.loadLibrary(System.java:1989)
> at Pj.nativecodes.<clinit>(nativecodes.java:6)
> at Pj.Launcher.main(Launcher.java:7)
> ```
> 
> I searched a solution for this error [Answer](https://stackoverflow.com/a/6092576/17777351).
> 
> How can I solve this error ?

If I remove qt framework code from my c++ file the jni lib works smoothly on my computer.

![jni qt](https://user-images.githubusercontent.com/96039278/166094262-ee07dca3-4a05-4fbe-bd2a-1147a3f66563.PNG)



How can I solve this issue ?

**Comment by lacasseio** [comment]
Please refer to https://github.com/nokeedev/gradle-native/discussions/607. Please be mindful in the future to avoid duplicated issues. The issue system is not a messaging system. It's much better to open a discussion to discuss an issue or keep the conversation on the community Slack. Using several points of entry into the same issue/discussion/conversation has a higher chance of not getting answered due to the fragmentation of the information across multiple systems.
