### ISSUE TITLE
Unexpected type for attribute 'dev.nokee.buildType' provided

### ISSUE THREAD

**Issue by pedrolamarao** [nokeedev/gradle-native#603]
I have a build which brings Nokee in with version `0.4.+` to keep up to date.

I have just observed a new version being pulled in.

After this, the build started failing with:

```
* What went wrong:
Could not determine the dependencies of task ':tool:link'.
> Could not resolve all artifacts for configuration ':tool:linkLibraries'.
   > Could not resolve project :api.
     Required by:
         project :tool
      > Unexpected type for attribute 'dev.nokee.buildType' provided. Expected a value of type dev.nokee.runtime.nativebase.BuildType but found a value of type dev.nokee.runtime.nativebase.DefaultBuildType.
```

Build scan: https://scans.gradle.com/s/pfdb7s7ghu5sm

**Comment by lacasseio** [comment]
That is unexpected. Let me have a closer look.

**Comment by lacasseio** [comment]
There is a bit of an unexpected version usage: https://scans.gradle.com/s/pfdb7s7ghu5sm/plugins#dev.nokee.native-runtime-23 Notice the same plugin is applied on two different projects with two different versions. That is most likely the issue. Hopefully, we can standardize the consumption of the Nokee plugins with https://github.com/nokeedev/gradle-native/issues/594. Could you copy here how you align the plugin versions?

I don't like the current solution but it should be along the line of https://github.com/nokeedev/gradle-native#install

**Comment by pedrolamarao** [comment]
This project uses a property to align versions. This happened during a version upgrade. The problem disappeared by itself. Maybe some caching issue somewhere.

**Comment by lacasseio** [comment]
Thanks for this input, I will try to see if we can detect such an issue with `nokee-version-management` plugin. Hopefully, we can check which versions are resolved and compare them to the version we expect.

**Comment by lacasseio** [comment]
I will close as the issue is gone and, as mentioned, most likely due to caching or something strange like that.
