### ISSUE TITLE
macOS: expose SDK_ROOT (~MacOSSdkPathLocator)

### ISSUE THREAD

**Issue by vlsi** [nokeedev/gradle-native#7]
`JavaNativeFoundation` can't be used directly since it is located under `$SDK_ROOT/System/Library/Frameworks/JavaVM.framework/Frameworks`

The workaround is to `@Inject org.gradle.nativeplatform.toolchain.internal.xcode.MacOSSdkPathLocator` which does not seem nice provided there's `.internal.`:
https://github.com/weisJ/darklaf/pull/72#issuecomment-599024403

The end goal is to be able to use `#include <JavaNativeFoundation/JavaNativeFoundation.h>`

**Comment by lacasseio** [comment]
Thanks for this issue. To help me understand, the JavaVM is a macOS only dependency that developers can choose to depend on but is not required for JNI development on macOS? I'm assuming it's also only available when targetting Mac desktop machine (macOS SDK). I couldn't find any reference to JavaVM framework on the iOS device family SDK. I also assume the dependency would follow what every tool chain you will be using for building the native code.

In theory, these dependencies should only be valid for variants that are targetting the macOS machines. It would mean the following:

1- However the dependency is declared, an helpful message could be notifying the users when the dependency is being miss-applied. For example,
```
library {
    dependencies {
        nativeImplementation javaNativeFoundation()
    }
}
```
or
```
library {
    variants.matching { targetMachine.operatingSystem.windows }.configureEach {
        dependencies {
            nativeImplementation javaNativeFoundation()
        }
    }
}
```
Should all show an error message mentioning to add the dependency for the specific macOS variant.

2- Dependency for the macOS variant should be added like the following:
```
library {
    variants.matching { targetMachine.operatingSystem.macOS }.configureEach {
        dependencies {
            nativeImplementation javaNativeFoundation()
        }
    }
}
```

I will most likely just reimplement `MacOSSdkPathLocator` in Nokee's plugin to have more flexibility on the implementation and integration with system/sdk dependencies.

**Comment by vlsi** [comment]
It is optional, however, it enables to have macOS-specific APIs.

For instance, if one wants to access mac-specific APIs (e.g. schedule work on mac's UI thread, propagate exceptions from Cocoa to Java), then JavaNativeFoundation is probably the only way to go.

See http://solutions.weblite.ca/tutorials/jni_osx/

E.g. OpenJDK uses JavaNativeFoundation (see https://bugs.openjdk.java.net/browse/JDK-8042959 )

**Comment by lacasseio** [comment]
Great thanks, if you have a small premade sample that you could point me toward, that would speed things up on my side.

**Comment by vlsi** [comment]
Frankly speaking, I've no idea there.

The use case in darklaf is to replace the default window title and draw a new one with Swing.
However, it turns out one does not simply get `nsWindow` pointer: https://github.com/weisJ/darklaf/blob/d567b6354d110137c4231a016c8e897bfce6fd53/macos/src/main/objectiveCpp/JNIDecorations.mm#L30-L49 , so it does not looks like the example qualifies as a simple one.

**Comment by lacasseio** [comment]
Right, thanks. I will find one and work on getting done. It may be more a cross-cutting feature of adding a framework as dependencies. I will do some thinking on how to solve this natively in the plugin. In the meantime, your workaround is the correct one. Although `MacOSSdkPathLocator` is internal, it is unlikely it will change.

**Comment by lacasseio** [comment]
I started to look at this in more detail and it's a bit more troublesome than anticipated. On one side, there is debt in the compiler infrastructure that prevents users from accessing important paths from the selected toolchain. This is a similar issue as the Windows SDK.

I spike something that would allow declaring dependencies on frameworks based on the name. The JavaNativeFoundation is tricky as it's an embedded framework inside the JavaVM framework. This means you need to know that you want a particular framework within another one. It breaks the producer/consumer contract. The resolver could search within the framework for embedded frameworks to include in the search but I'm unsure at this point if that would include frameworks that should be private.

I will think about this a bit more, maybe there is a better alternative in the short term.

**Comment by lacasseio** [comment]
According to Mac Technology Overview, [the JavaVM framework is deprecated since 10.7](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html). According to the Framework Programming Guide, [we should not reference subframeworks directly](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Tasks/IncludingFrameworks.html#//apple_ref/doc/uid/20002257-97149). However, all reference to JavaNativeFoundation framework use direct reference. :-(

**Comment by lacasseio** [comment]
Hmmm, after a good night of sleep, we could model subframeworks as capabilities. Meaning you want the JavaVM framework with the JavaNativeFoundation capabilities. The declaration would look something like:
```
library {
    dependencies {
        nativeImplementation framework('JavaVM:10.15') {
            capabilities {
                requireCapability('JavaVM:JavaNativeFoundation')
            }
        }
    }
}
```

It really seems that JavaVM is an older framework and doesn't behave as recommended by Apple. The capability would notify the resolver to look inside for subframework and allow you to wire your build properly without compromising the cross-cutting feature of framework resolution. It would also allow you to do the same for other umbrella frameworks, although not recommended by Apple.

**Comment by lacasseio** [comment]
It seems to be working pretty well with the capabilities. I will clean up the spike add some test coverage and push it in a nightly so you can test it. There will be limitations but it should be good enough for this use case. We can expand the solution in future commits.

**Comment by lacasseio** [comment]
This is delivered in 0.2.
