### ISSUE TITLE
PBXSourceTree should support any build settings value

### ISSUE THREAD

**Issue by lacasseio** [nokeedev/gradle-native#701]
Any non-square bracket value will try to resolve the `PBXFileReference` from the matching build settings. Meaning I could have `sourceTree = FOO_BAR, path = ../my-file.txt`, and it would essentially mean `$(FOO_BAR)/../my-file.txt`.

We need to convert `PBXSourceTree` to something other than an enum. We also have the open question regarding the format of the `sourceTree` value. We can assume it should be build settings compatible which is usually upper case no space, but it may be of a different format.

**Comment by enaess** [comment]
Following
