### ISSUE TITLE
Publish dev.gradleplugins:gradle-api:6.9.3 to Maven Central

### ISSUE THREAD

**Issue by aalmiray** [nokeedev/gradle-native#743]
Apologies if this is not the correct repository to raise such an issue but I've seen the `gradle-api` subproject inside this project thus I assumed this would be the place to ask for `dev.gradleplugins:gradle-api:6.9.3` to be published to Maven Central.

As of today the latest published version for the 6.x series is `6.9.2`. https://mvnrepository.com/artifact/dev.gradleplugins/gradle-api/6.9.2

**Comment by lacasseio** [comment]
This is a great place as well. I had the feeling I forgot to release v6.9.3. It should appear soon on Maven Central.

**Comment by aalmiray** [comment]
Thank you 😄
